### PR TITLE
Build and publishes the book

### LINKED ISSUE #2: [suggestion] Deploy PDF through CI
Just a suggestion. This repo is great but I think it could benefit from having a button to download the PDF in the readme (without the PDF itself being version-controlled, just the LaTeX). I have not done this myself, but I think this could be done by following, e.g., [HowTo-Deploy-LaTeX-Documents](https://github.com/SimonWaldherr/HowTo-Deploy-LaTeX-Documents). 

---

**EDIT**: I just realized the PDFs are available through releases. So CI could simply automate that process. And having the badge/button on the readme is still a suggestion 🙂

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/introocean/introocean-en/issues/2

I also add a bare minimum pre-commit hook that runs codespell, used in #5, and fixes trailing white spaces and end of file new lines.

### CODE REVIEW

**Comment by ocefpaf** [comment]
One can see how this GitHub action will work in https://github.com/ocefpaf/introocean-en/actions/runs/3138520066. The zipped artifact has the PDF book. When issues a tagged release that would be uploaded to as a GitHub release artifact.

**Comment by koldunovn** [comment]
@ocefpaf thanks a LOT!

**Comment by ocefpaf** [comment]
Do you want to tag a release to test it out?

**Comment by koldunovn** [comment]
> Do you want to tag a release to test it out?

Works :)

**Comment by sergeykorop** [comment]
It seems be convenient to keep naming releases with a more meaningful names including release date, similarly to previous ones.

This could help the readers, e.g. to cite some particular revision by its name, especially when book file is stored somewhere outside the GitHub repository.

**Comment by ocefpaf** [comment]
> It seems be convenient to keep naming releases with a more meaningful names including release date, similarly to previous ones.

It should be relatively easy to implement that. I'll give it a try tomorrow if no one beats me to it.

**Pull request merged**
